### ISSUE TITLE
Resizable grid

### ISSUE THREAD

**Issue by Alex40144** [PirateGame/Pirate-Game-Backend#14]

**Comment by portaljumper007** [comment]
https://vuejsexamples.com/tag/drag/
http://dsmorse.github.io/gridster.js/

**Comment by portaljumper007** [comment]
https://gridstackjs.com/

**Comment by OwenPauptit** [comment]
Does this just change the number of 200s or?

**Comment by portaljumper007** [comment]
I think that would make sense @OwenPauptit yes.
