### ISSUE TITLE
when creating a player, set gameFound if game exists

### ISSUE THREAD

**Issue by Alex40144** [PirateGame/Pirate-Game-Backend#41]
check if game exists when creating player

**Comment by portaljumper007** [comment]
Can you explain what you mean by this in more detail? @Alex40144

**Comment by Alex40144** [comment]
When creating a client it connects it to a game, bit there is no validation that this game exists from what I called find.

**Comment by portaljumper007** [comment]
@Alex40144 It's only possible to create a client on the backend if it's a """child""" of a game, so there's no need for validation?

**Comment by Alex40144** [comment]
Ah, so I must of been doing the wrong thing. How do you create a player then?

**Comment by portaljumper007** [comment]
@Alex40144 Go on discord, I'll show you how to use it all properly ;D
