### ISSUE TITLE
Function to set the skull+crossbones attributes

### ISSUE THREAD

**Issue by Alex40144** [PirateGame/Pirate-Game-Backend#42]
these could be in the form of a pirate clan and a pirate ship. instead of the ABC123 thing

**Comment by portaljumper007** [comment]
Currently it's randomised, in the code...
`"column":random.randint(0,self.game.about["gridDim"][0]-1), "row":random.randint(0,self.game.about["gridDim"][1]-1)`

**Comment by portaljumper007** [comment]
"these could be in the form of a pirate clan and a pirate ship" this is a good idea, but is it necessary? Discuss it with the people on the discord perhaps? @Alex40144

**Comment by portaljumper007** [comment]
Say hello to the one and only all-purpose **alterClients** function...
`def alterClients(gameName, clientNames, alterations):
    for clientName in clientNames:
        if clientName in games[gameName].about["clients"]:
            for key,value in alterations.items():
                if key in games[gameName].about["clients"][clientName].about:
                    games[gameName].about["clients"][clientName].about[key] = value
                else:
                    success.append("Key", key, "doesn't exist for value", value, "to be assigned to.")
        else:
            for a in alterations.items():
                success.append("Client", clientName, "doesn't exist.")`
