### ISSUE TITLE
Basic Game Board Page with ability to add items to board

### ISSUE THREAD

**Issue by Alex40144** [PirateGame/Pirate-Game-Backend#6]
randomization and drag/drop

**Comment by ThomasAWood** [comment]
So this is dragging and dropping objects onto the board or clicking a button and it automatically adding them?
But this won't have any actual funcitonality behind it?

**Comment by portaljumper007** [comment]
Me and Owen have decided on clicking an object to move, and then clicking the destination object, which will displace the source object to the new location. This is preferable to the drag and drop HTML5 technology as it will work on mobile, and is just a bit easier too hopefully.
